# Generated by Django 2.2.4 on 2019-09-28 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTodo', '0002_hotelbooking_newtodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 20, 17, 5, 966001)),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 20, 17, 5, 965976)),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_details',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newtodo',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 20, 17, 5, 965252)),
        ),
    ]
