# Generated by Django 2.2.4 on 2019-09-28 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTodo', '0003_auto_20190928_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 20, 23, 31, 144423)),
        ),
        migrations.AlterField(
            model_name='newtodo',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 20, 23, 31, 143773)),
        ),
    ]
